spring:
  thymeleaf:
    #    enabled: true  #开启thymeleaf视图解析
    #    encoding: utf-8  #编码
    #    prefix: classpath:/templates/  #前缀
    cache: false  #是否使用缓存
  #    mode: HTML  #严格的HTML语法模式
  #    suffix: .html  #后缀名
  devtools:
    restart:
      enabled: true # 配置热部署
      additional-paths: src/main/java
      exclude: WEB-INF/**
server:
  port: 8891
